development:
  bucket: shares-container
  access_key_id: AKIAJFVOO7GITNL6DDZA
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com

production:
  bucket: shares-container
  access_key_id: AKIAJFVOO7GITNL6DDZA
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com